-- Update the notifications table type check constraint to include all new notification types
-- Run this in your Supabase SQL editor or database console

-- First, drop the existing constraint
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;

-- Then, add the new constraint with all allowed types
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check CHECK (type IN (
  'order_placed',
  'order_accepted',
  'order_cancelled',
  'rental_order_placed',
  'delivery_assigned',
  'delivery_partner_assigned',
  'delivery_status_updated',
  'out_for_pickup',
  'item_picked_up',
  'product_picked_up',
  'out_for_delivery',
  'product_out_for_delivery',
  'item_delivered',
  'product_delivered',
  'return_initiated',
  'item_returned',
  'product_returned',
  'payment_received',
  'payment_failed',
  'refund_processed',
  'refund_payout_released',
  'security_deposit_released',
  'security_deposit_deducted',
  'payout_sent',
  'late_fee_applied',
  'late_return',
  'damage_claim_reported',
  'damage_reported',
  'product_returned_damaged',
  'damage_claim_approved',
  'damage_claim_rejected',
  'product_approved',
  'product_rejected',
  'product_review_received',
  'product_booked',
  'product_listed',
  'cart_item_expiring',
  'product_available_again',
  'kyc_approved',
  'kyc_rejected',
  'kyc_documents_required',
  'promo_code_available',
  'referral_reward_earned',
  'referral_signup_complete',
  'rental_ending_soon',
  'return_reminder',
  'try_on_scheduled',
  'rental_confirmed',
  'new_delivery_assignment',
  'system_announcement',
  'custom',
  'new_user_registered'
));